/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as ScheduleIdentifierImport } from './routes/$scheduleIdentifier'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as FacultyIdentifierIndexImport } from './routes/$facultyIdentifier/index'
import { Route as AdminMeetingsIndexImport } from './routes/admin/meetings/index'
import { Route as FacultyIdentifierEventIdentifierIndexImport } from './routes/$facultyIdentifier/$eventIdentifier/index'
import { Route as DashboardScheduleFacultyIdImport } from './routes/dashboard/schedule/$facultyId'
import { Route as FacultyIdentifierEventIdentifierAuthenticatedImport } from './routes/$facultyIdentifier/$eventIdentifier/_authenticated'
import { Route as AdminAvailabilityScheduleIndexImport } from './routes/admin/availability/schedule/index'
import { Route as AdminAvailabilityScheduleScheduleIdImport } from './routes/admin/availability/schedule/$scheduleId'
import { Route as FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeImport } from './routes/$facultyIdentifier/$eventIdentifier/_authenticated/$appointmentDatetime'

// Create Virtual Routes

const FacultyIdentifierEventIdentifierImport = createFileRoute(
  '/$facultyIdentifier/$eventIdentifier',
)()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const ScheduleIdentifierRoute = ScheduleIdentifierImport.update({
  id: '/$scheduleIdentifier',
  path: '/$scheduleIdentifier',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FacultyIdentifierEventIdentifierRoute =
  FacultyIdentifierEventIdentifierImport.update({
    id: '/$facultyIdentifier/$eventIdentifier',
    path: '/$facultyIdentifier/$eventIdentifier',
    getParentRoute: () => rootRoute,
  } as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const FacultyIdentifierIndexRoute = FacultyIdentifierIndexImport.update({
  id: '/$facultyIdentifier/',
  path: '/$facultyIdentifier/',
  getParentRoute: () => rootRoute,
} as any)

const AdminMeetingsIndexRoute = AdminMeetingsIndexImport.update({
  id: '/admin/meetings/',
  path: '/admin/meetings/',
  getParentRoute: () => rootRoute,
} as any)

const FacultyIdentifierEventIdentifierIndexRoute =
  FacultyIdentifierEventIdentifierIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => FacultyIdentifierEventIdentifierRoute,
  } as any)

const DashboardScheduleFacultyIdRoute = DashboardScheduleFacultyIdImport.update(
  {
    id: '/dashboard/schedule/$facultyId',
    path: '/dashboard/schedule/$facultyId',
    getParentRoute: () => rootRoute,
  } as any,
)

const FacultyIdentifierEventIdentifierAuthenticatedRoute =
  FacultyIdentifierEventIdentifierAuthenticatedImport.update({
    id: '/_authenticated',
    getParentRoute: () => FacultyIdentifierEventIdentifierRoute,
  } as any)

const AdminAvailabilityScheduleIndexRoute =
  AdminAvailabilityScheduleIndexImport.update({
    id: '/admin/availability/schedule/',
    path: '/admin/availability/schedule/',
    getParentRoute: () => rootRoute,
  } as any)

const AdminAvailabilityScheduleScheduleIdRoute =
  AdminAvailabilityScheduleScheduleIdImport.update({
    id: '/admin/availability/schedule/$scheduleId',
    path: '/admin/availability/schedule/$scheduleId',
    getParentRoute: () => rootRoute,
  } as any)

const FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeRoute =
  FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeImport.update(
    {
      id: '/$appointmentDatetime',
      path: '/$appointmentDatetime',
      getParentRoute: () => FacultyIdentifierEventIdentifierAuthenticatedRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$scheduleIdentifier': {
      id: '/$scheduleIdentifier'
      path: '/$scheduleIdentifier'
      fullPath: '/$scheduleIdentifier'
      preLoaderRoute: typeof ScheduleIdentifierImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/$facultyIdentifier/': {
      id: '/$facultyIdentifier/'
      path: '/$facultyIdentifier'
      fullPath: '/$facultyIdentifier'
      preLoaderRoute: typeof FacultyIdentifierIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/$facultyIdentifier/$eventIdentifier': {
      id: '/$facultyIdentifier/$eventIdentifier'
      path: '/$facultyIdentifier/$eventIdentifier'
      fullPath: '/$facultyIdentifier/$eventIdentifier'
      preLoaderRoute: typeof FacultyIdentifierEventIdentifierImport
      parentRoute: typeof rootRoute
    }
    '/$facultyIdentifier/$eventIdentifier/_authenticated': {
      id: '/$facultyIdentifier/$eventIdentifier/_authenticated'
      path: '/$facultyIdentifier/$eventIdentifier'
      fullPath: '/$facultyIdentifier/$eventIdentifier'
      preLoaderRoute: typeof FacultyIdentifierEventIdentifierAuthenticatedImport
      parentRoute: typeof FacultyIdentifierEventIdentifierRoute
    }
    '/dashboard/schedule/$facultyId': {
      id: '/dashboard/schedule/$facultyId'
      path: '/dashboard/schedule/$facultyId'
      fullPath: '/dashboard/schedule/$facultyId'
      preLoaderRoute: typeof DashboardScheduleFacultyIdImport
      parentRoute: typeof rootRoute
    }
    '/$facultyIdentifier/$eventIdentifier/': {
      id: '/$facultyIdentifier/$eventIdentifier/'
      path: '/'
      fullPath: '/$facultyIdentifier/$eventIdentifier/'
      preLoaderRoute: typeof FacultyIdentifierEventIdentifierIndexImport
      parentRoute: typeof FacultyIdentifierEventIdentifierImport
    }
    '/admin/meetings/': {
      id: '/admin/meetings/'
      path: '/admin/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AdminMeetingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/$facultyIdentifier/$eventIdentifier/_authenticated/$appointmentDatetime': {
      id: '/$facultyIdentifier/$eventIdentifier/_authenticated/$appointmentDatetime'
      path: '/$appointmentDatetime'
      fullPath: '/$facultyIdentifier/$eventIdentifier/$appointmentDatetime'
      preLoaderRoute: typeof FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeImport
      parentRoute: typeof FacultyIdentifierEventIdentifierAuthenticatedImport
    }
    '/admin/availability/schedule/$scheduleId': {
      id: '/admin/availability/schedule/$scheduleId'
      path: '/admin/availability/schedule/$scheduleId'
      fullPath: '/admin/availability/schedule/$scheduleId'
      preLoaderRoute: typeof AdminAvailabilityScheduleScheduleIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/availability/schedule/': {
      id: '/admin/availability/schedule/'
      path: '/admin/availability/schedule'
      fullPath: '/admin/availability/schedule'
      preLoaderRoute: typeof AdminAvailabilityScheduleIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface FacultyIdentifierEventIdentifierAuthenticatedRouteChildren {
  FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeRoute: typeof FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeRoute
}

const FacultyIdentifierEventIdentifierAuthenticatedRouteChildren: FacultyIdentifierEventIdentifierAuthenticatedRouteChildren =
  {
    FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeRoute:
      FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeRoute,
  }

const FacultyIdentifierEventIdentifierAuthenticatedRouteWithChildren =
  FacultyIdentifierEventIdentifierAuthenticatedRoute._addFileChildren(
    FacultyIdentifierEventIdentifierAuthenticatedRouteChildren,
  )

interface FacultyIdentifierEventIdentifierRouteChildren {
  FacultyIdentifierEventIdentifierAuthenticatedRoute: typeof FacultyIdentifierEventIdentifierAuthenticatedRouteWithChildren
  FacultyIdentifierEventIdentifierIndexRoute: typeof FacultyIdentifierEventIdentifierIndexRoute
}

const FacultyIdentifierEventIdentifierRouteChildren: FacultyIdentifierEventIdentifierRouteChildren =
  {
    FacultyIdentifierEventIdentifierAuthenticatedRoute:
      FacultyIdentifierEventIdentifierAuthenticatedRouteWithChildren,
    FacultyIdentifierEventIdentifierIndexRoute:
      FacultyIdentifierEventIdentifierIndexRoute,
  }

const FacultyIdentifierEventIdentifierRouteWithChildren =
  FacultyIdentifierEventIdentifierRoute._addFileChildren(
    FacultyIdentifierEventIdentifierRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$scheduleIdentifier': typeof ScheduleIdentifierRoute
  '': typeof AuthenticatedRoute
  '/$facultyIdentifier': typeof FacultyIdentifierIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$facultyIdentifier/$eventIdentifier': typeof FacultyIdentifierEventIdentifierAuthenticatedRouteWithChildren
  '/dashboard/schedule/$facultyId': typeof DashboardScheduleFacultyIdRoute
  '/$facultyIdentifier/$eventIdentifier/': typeof FacultyIdentifierEventIdentifierIndexRoute
  '/admin/meetings': typeof AdminMeetingsIndexRoute
  '/$facultyIdentifier/$eventIdentifier/$appointmentDatetime': typeof FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeRoute
  '/admin/availability/schedule/$scheduleId': typeof AdminAvailabilityScheduleScheduleIdRoute
  '/admin/availability/schedule': typeof AdminAvailabilityScheduleIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$scheduleIdentifier': typeof ScheduleIdentifierRoute
  '': typeof AuthenticatedRoute
  '/$facultyIdentifier': typeof FacultyIdentifierIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$facultyIdentifier/$eventIdentifier': typeof FacultyIdentifierEventIdentifierIndexRoute
  '/dashboard/schedule/$facultyId': typeof DashboardScheduleFacultyIdRoute
  '/admin/meetings': typeof AdminMeetingsIndexRoute
  '/$facultyIdentifier/$eventIdentifier/$appointmentDatetime': typeof FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeRoute
  '/admin/availability/schedule/$scheduleId': typeof AdminAvailabilityScheduleScheduleIdRoute
  '/admin/availability/schedule': typeof AdminAvailabilityScheduleIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$scheduleIdentifier': typeof ScheduleIdentifierRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/$facultyIdentifier/': typeof FacultyIdentifierIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$facultyIdentifier/$eventIdentifier': typeof FacultyIdentifierEventIdentifierRouteWithChildren
  '/$facultyIdentifier/$eventIdentifier/_authenticated': typeof FacultyIdentifierEventIdentifierAuthenticatedRouteWithChildren
  '/dashboard/schedule/$facultyId': typeof DashboardScheduleFacultyIdRoute
  '/$facultyIdentifier/$eventIdentifier/': typeof FacultyIdentifierEventIdentifierIndexRoute
  '/admin/meetings/': typeof AdminMeetingsIndexRoute
  '/$facultyIdentifier/$eventIdentifier/_authenticated/$appointmentDatetime': typeof FacultyIdentifierEventIdentifierAuthenticatedAppointmentDatetimeRoute
  '/admin/availability/schedule/$scheduleId': typeof AdminAvailabilityScheduleScheduleIdRoute
  '/admin/availability/schedule/': typeof AdminAvailabilityScheduleIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$scheduleIdentifier'
    | ''
    | '/$facultyIdentifier'
    | '/admin'
    | '/dashboard'
    | '/$facultyIdentifier/$eventIdentifier'
    | '/dashboard/schedule/$facultyId'
    | '/$facultyIdentifier/$eventIdentifier/'
    | '/admin/meetings'
    | '/$facultyIdentifier/$eventIdentifier/$appointmentDatetime'
    | '/admin/availability/schedule/$scheduleId'
    | '/admin/availability/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$scheduleIdentifier'
    | ''
    | '/$facultyIdentifier'
    | '/admin'
    | '/dashboard'
    | '/$facultyIdentifier/$eventIdentifier'
    | '/dashboard/schedule/$facultyId'
    | '/admin/meetings'
    | '/$facultyIdentifier/$eventIdentifier/$appointmentDatetime'
    | '/admin/availability/schedule/$scheduleId'
    | '/admin/availability/schedule'
  id:
    | '__root__'
    | '/'
    | '/$scheduleIdentifier'
    | '/_authenticated'
    | '/$facultyIdentifier/'
    | '/admin/'
    | '/dashboard/'
    | '/$facultyIdentifier/$eventIdentifier'
    | '/$facultyIdentifier/$eventIdentifier/_authenticated'
    | '/dashboard/schedule/$facultyId'
    | '/$facultyIdentifier/$eventIdentifier/'
    | '/admin/meetings/'
    | '/$facultyIdentifier/$eventIdentifier/_authenticated/$appointmentDatetime'
    | '/admin/availability/schedule/$scheduleId'
    | '/admin/availability/schedule/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScheduleIdentifierRoute: typeof ScheduleIdentifierRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  FacultyIdentifierIndexRoute: typeof FacultyIdentifierIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FacultyIdentifierEventIdentifierRoute: typeof FacultyIdentifierEventIdentifierRouteWithChildren
  DashboardScheduleFacultyIdRoute: typeof DashboardScheduleFacultyIdRoute
  AdminMeetingsIndexRoute: typeof AdminMeetingsIndexRoute
  AdminAvailabilityScheduleScheduleIdRoute: typeof AdminAvailabilityScheduleScheduleIdRoute
  AdminAvailabilityScheduleIndexRoute: typeof AdminAvailabilityScheduleIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScheduleIdentifierRoute: ScheduleIdentifierRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  FacultyIdentifierIndexRoute: FacultyIdentifierIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FacultyIdentifierEventIdentifierRoute:
    FacultyIdentifierEventIdentifierRouteWithChildren,
  DashboardScheduleFacultyIdRoute: DashboardScheduleFacultyIdRoute,
  AdminMeetingsIndexRoute: AdminMeetingsIndexRoute,
  AdminAvailabilityScheduleScheduleIdRoute:
    AdminAvailabilityScheduleScheduleIdRoute,
  AdminAvailabilityScheduleIndexRoute: AdminAvailabilityScheduleIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$scheduleIdentifier",
        "/_authenticated",
        "/$facultyIdentifier/",
        "/admin/",
        "/dashboard/",
        "/$facultyIdentifier/$eventIdentifier",
        "/dashboard/schedule/$facultyId",
        "/admin/meetings/",
        "/admin/availability/schedule/$scheduleId",
        "/admin/availability/schedule/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$scheduleIdentifier": {
      "filePath": "$scheduleIdentifier.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx"
    },
    "/$facultyIdentifier/": {
      "filePath": "$facultyIdentifier/index.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/$facultyIdentifier/$eventIdentifier": {
      "filePath": "$facultyIdentifier/$eventIdentifier",
      "children": [
        "/$facultyIdentifier/$eventIdentifier/_authenticated",
        "/$facultyIdentifier/$eventIdentifier/"
      ]
    },
    "/$facultyIdentifier/$eventIdentifier/_authenticated": {
      "filePath": "$facultyIdentifier/$eventIdentifier/_authenticated.tsx",
      "parent": "/$facultyIdentifier/$eventIdentifier",
      "children": [
        "/$facultyIdentifier/$eventIdentifier/_authenticated/$appointmentDatetime"
      ]
    },
    "/dashboard/schedule/$facultyId": {
      "filePath": "dashboard/schedule/$facultyId.tsx"
    },
    "/$facultyIdentifier/$eventIdentifier/": {
      "filePath": "$facultyIdentifier/$eventIdentifier/index.tsx",
      "parent": "/$facultyIdentifier/$eventIdentifier"
    },
    "/admin/meetings/": {
      "filePath": "admin/meetings/index.tsx"
    },
    "/$facultyIdentifier/$eventIdentifier/_authenticated/$appointmentDatetime": {
      "filePath": "$facultyIdentifier/$eventIdentifier/_authenticated/$appointmentDatetime.tsx",
      "parent": "/$facultyIdentifier/$eventIdentifier/_authenticated"
    },
    "/admin/availability/schedule/$scheduleId": {
      "filePath": "admin/availability/schedule/$scheduleId.tsx"
    },
    "/admin/availability/schedule/": {
      "filePath": "admin/availability/schedule/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
